sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start creating an image with dockerfile"
  - docker build -t weightle55/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true weightle55/docker-react-app npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-2"  
  app: "docker-react-app"
  env: "Docker-react-app-env"
  bucket_name: "elasticbeanstalk-ap-southeast-2-533267340364" #s3 로 가서 확인
  bucket_path: "docker-react-app" # 이름과 똑같이
  on:
    branch: master
access_key_id: $AWS_ACCESS_KEY
secret_access_key: $AWS_SECRET_ACCESS_KEY